/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Suit { 
  SPADES, DIAMONDS, CLUBS, HEARTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"example\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"CLUBS\",\"HEARTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}