/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.proto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Suit {
  SPADES, HEARTS, DIAMONDS, CLUBS  ;
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.JsonSchemaParser.parseInternal("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"example.proto\",\"symbols\":[\"SPADES\",\"HEARTS\",\"DIAMONDS\",\"CLUBS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
