/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example;
@org.apache.avro.specific.AvroGenerated
public enum Suit implements org.apache.avro.generic.GenericEnumSymbol<Suit> {
  SPADES, DIAMONDS, CLUBS, HEARTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.JsonSchemaParser.parseInternal("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"example\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"CLUBS\",\"HEARTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
