/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package example.idl.java.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum DefaultEnum { 
  SPADES, DIAMONDS, CLUBS, HEARTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DefaultEnum\",\"namespace\":\"example.idl.java.model\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"CLUBS\",\"HEARTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
