/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package test;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Direction { 
  NORTH, SOUTH, EAST, WEST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Direction\",\"namespace\":\"test\",\"symbols\":[\"NORTH\",\"SOUTH\",\"EAST\",\"WEST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
